### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by kumakichi**

### CODE REVIEW

**Comment by kumakichi** [comment]
<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">


<colgroup>
<col  class="org-left" />

<col  class="org-right" />

<col  class="org-right" />
</colgroup>
<tbody>
<tr>
<td class="org-left">lib</td>
<td class="org-right">old</td>
<td class="org-right">new</td>
</tr>


<tr>
<td class="org-left">pdfjs-dist</td>
<td class="org-right">2.0.489</td>
<td class="org-right">2.8.335</td>
</tr>


<tr>
<td class="org-left">babel-eslint</td>
<td class="org-right">7.1.1</td>
<td class="org-right">10.1.0</td>
</tr>


<tr>
<td class="org-left">copy-webpack-plugin</td>
<td class="org-right">4.0.1</td>
<td class="org-right">9.0.1</td>
</tr>


<tr>
<td class="org-left">eslint</td>
<td class="org-right">4.18.2</td>
<td class="org-right">7.30.0</td>
</tr>


<tr>
<td class="org-left">file-loader</td>
<td class="org-right">0.10.0</td>
<td class="org-right">6.2.0</td>
</tr>


<tr>
<td class="org-left">html-webpack-plugin</td>
<td class="org-right">2.22.0</td>
<td class="org-right">5.3.2</td>
</tr>


<tr>
<td class="org-left">webpack</td>
<td class="org-right">3.11.0</td>
<td class="org-right">5.42.0</td>
</tr>


<tr>
<td class="org-left">webpack-cli</td>
<td class="org-right">2.0.15</td>
<td class="org-right">4.7.2</td>
</tr>


<tr>
<td class="org-left">webpack-dev-server</td>
<td class="org-right">2.11.1</td>
<td class="org-right">3.11.2</td>
</tr>
</tbody>
</table>

**Comment by jzillmann** [comment]
Hey @kumakichi , checked this out and when I'm running `npm run watch` I get 
```
npm run watch 

> pdf-to-markdown@0.1.2 watch
> webpack -d --watch

[webpack-cli] Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.devtool should match pattern "^(inline-|hidden-|eval-)?(nosources-)?(cheap-(module-)?)?source-map$".
   BREAKING CHANGE since webpack 5: The devtool option is more strict.
   Please strictly follow the order of the keywords in the pattern.
```

Any idea ?

**Comment by kumakichi** [comment]
It's wierd, I just made a clean clone of my repo and tested, it works

But I found someone has [the same problem](https://masahiro.me/2020/11/configuration-devtool-should-match-pattern-inline-hidden-eval-nosources-cheap-module-source-map/), he just removed `-d`

But both `webpack -d --watch` and `webpack --watch` work for me

**Comment by jzillmann** [comment]
Ok, `--mode development` seems to do the trick!
Thanks for your work!

**Pull request merged**
